### ISSUE TITLE
Provide nice error message when no simulator can be found

### ISSUE THREAD

**Issue by cmarqu** [VUnit/vunit#125]
When I don't have any of the supported simulators in $PATH, I get the following instead of a nice eror message:
```
Traceback (most recent call last):
  File "./run_vunit.py", line 19, in <module>
    vunit_prj = VUnit.from_argv()
  File "/home/marquardt/tools/vunit/vunit/ui.py", line 155, in from_argv
    args = VUnitCLI().parse_args(argv=argv)
  File "/home/marquardt/tools/vunit/vunit/vunit_cli.py", line 54, in __init__
    self.parser = _create_argument_parser(description)
  File "/home/marquardt/tools/vunit/vunit/vunit_cli.py", line 141, in _create_argument_parser
    for_all_simulators=for_documentation)
  File "/home/marquardt/tools/vunit/vunit/simulator_factory.py", line 77, in add_arguments
    if for_all_simulators or cls.select_simulator().supports_gui_flag:
AttributeError: 'NoneType' object has no attribute 'supports_gui_flag'

```

**Comment by kraigher** [comment]
This is a regression. After fixing #129 you now get a message saying there were no simulators detected on the PATH environment variable.
