### ISSUE TITLE
FileNotFoundError when executing VUnit with run.py --compile

### ISSUE THREAD

**Issue by curiousengineer** [VUnit/vunit#700]
It is not clear why but I am getting error with vu.add_osvvm() and vu.add_verification_components() and even if these are skipped, errors still occur when vu.main() is executed:

Traceback (most recent call last):
  File "run.py", line 306, in <module>
    main()
  File "run.py", line 157, in main
    vu.add_osvvm()
  File "c:\my_designs\fpga_design\deps\vunit\vunit\ui.py", line 975, in add_osvvm
    self._builtins.add("osvvm")
  File "c:\my_designs\fpga_design\deps\vunit\vunit\builtins.py", line 41, in add
    self._builtins_adder.add(name, args)
  File "c:\my_designs\fpga_design\deps\vunit\vunit\builtins.py", line 216, in add
    function(**args)
  File "c:\my_designs\fpga_design\deps\vunit\vunit\builtins.py", line 124, in _add_osvvm
    supports_vhdl_package_generics = self._simulator_class.supports_vhdl_package_generics()
  File "c:\my_designs\fpga_design\deps\vunit\vunit\activehdl_interface.py", line 67, in supports_vhdl_package_generics
    proc = Process([join(cls.find_prefix(), 'vcom'), '-version'], env=cls.get_env())
  File "c:\my_designs\fpga_design\deps\vunit\vunit\ostools.py", line 118, in __init__
    creationflags=subprocess.CREATE_NEW_PROCESS_GROUP)
  File "c:\users\the_user\appdata\local\programs\python\python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\the_user\appdata\local\programs\python\python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
Exception ignored in: <function Process.__del__ at 0x02F35ED0>
Traceback (most recent call last):
  File "c:\my_designs\fpga_design\deps\vunit\vunit\ostools.py", line 243, in __del__
    self.terminate()
  File "c:\my_designs\fpga_design\deps\vunit\vunit\ostools.py", line 219, in terminate
    if self._process.poll() is None:
AttributeError: 'Process' object has no attribute '_process'
make: *** [Makefile:16: compile] Error 1

Traceback (most recent call last):
  File "run.py", line 306, in <module>
    main()
  File "run.py", line 159, in main
    vu.add_verification_components()
  File "c:\my_designs\fpga_design\deps\vunit\vunit\ui.py", line 969, in add_verification_components
    self._builtins.add("verification_components")
  File "c:\my_designs\fpga_design\deps\vunit\vunit\builtins.py", line 41, in add
    self._builtins_adder.add(name, args)
  File "c:\my_designs\fpga_design\deps\vunit\vunit\builtins.py", line 215, in add
    self.add(dep_name)
  File "c:\my_designs\fpga_design\deps\vunit\vunit\builtins.py", line 216, in add
    function(**args)
  File "c:\my_designs\fpga_design\deps\vunit\vunit\builtins.py", line 124, in _add_osvvm
    supports_vhdl_package_generics = self._simulator_class.supports_vhdl_package_generics()
  File "c:\my_designs\fpga_design\deps\vunit\vunit\activehdl_interface.py", line 67, in supports_vhdl_package_generics
    proc = Process([join(cls.find_prefix(), 'vcom'), '-version'], env=cls.get_env())
  File "c:\my_designs\fpga_design\deps\vunit\vunit\ostools.py", line 118, in __init__
    creationflags=subprocess.CREATE_NEW_PROCESS_GROUP)
  File "c:\users\the_user\appdata\local\programs\python\python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\the_user\appdata\local\programs\python\python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
Exception ignored in: <function Process.__del__ at 0x03795ED0>
Traceback (most recent call last):
  File "c:\my_designs\fpga_design\deps\vunit\vunit\ostools.py", line 243, in __del__
    self.terminate()
  File "c:\my_designs\fpga_design\deps\vunit\vunit\ostools.py", line 219, in terminate
    if self._process.poll() is None:
AttributeError: 'Process' object has no attribute '_process'
make: *** [Makefile:16: compile] Error 1

Traceback (most recent call last):
  File "c:\my_designs\fpga_design\deps\vunit\vunit\ui.py", line 761, in main
    all_ok = self._main(post_run)
  File "c:\my_designs\fpga_design\deps\vunit\vunit\ui.py", line 800, in _main
    return self._main_compile_only()
  File "c:\my_designs\fpga_design\deps\vunit\vunit\ui.py", line 876, in _main_compile_only
    self._compile(simulator_if)
  File "c:\my_designs\fpga_design\deps\vunit\vunit\ui.py", line 908, in _compile
    printer=self._printer)
  File "c:\my_designs\fpga_design\deps\vunit\vunit\simulator_interface.py", line 159, in compile_project
    self.setup_library_mapping(project)
  File "c:\my_designs\fpga_design\deps\vunit\vunit\activehdl_interface.py", line 90, in setup_library_mapping
    self.create_library(library.name, library.directory, mapped_libraries)
  File "c:\my_designs\fpga_design\deps\vunit\vunit\activehdl_interface.py", line 140, in create_library
    env=self.get_env())
  File "c:\my_designs\fpga_design\deps\vunit\vunit\ostools.py", line 118, in __init__
    creationflags=subprocess.CREATE_NEW_PROCESS_GROUP)
  File "c:\users\the_user\appdata\local\programs\python\python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\the_user\appdata\local\programs\python\python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
Exception ignored in: <function Process.__del__ at 0x02FA5ED0>
Traceback (most recent call last):
  File "c:\my_designs\fpga_design\deps\vunit\vunit\ostools.py", line 243, in __del__
    self.terminate()
  File "c:\my_designs\fpga_design\deps\vunit\vunit\ostools.py", line 219, in terminate
    if self._process.poll() is None:
AttributeError: 'Process' object has no attribute '_process'
make: *** [Makefile:16: compile] Error 1

What could be the meaning of this? I have uninstalled and reinstalled Python, a few different versions of Python. Also, I have used current a another older version of VUnit but these problems still happen. It is not clear why they are happening now as everything was working fine until last week.

**Comment by curiousengineer** [comment]
Please delete this
